name: equity-insights-dashboard
channels:
  - conda-forge
dependencies:
  - jupyter=1.0.0
  - jupyterlab=2.1.1
  - pandas=1.0.3
  - numpy=1.18.1
  - pymc3=3.8
  - theano=1.0.4
  - scipy=1.2.1
  - seaborn=0.10.0
  - matplotlib=3.2.1
  - scikit-learn=0.22.2.post1
  - mkl-service=2.3.0
  - statsmodels=0.11.1
  - jupyter_contrib_nbextensions=0.5.1
  - xlrd=1.2.0


