name: causal_discovery
channels:
  - conda-forge
dependencies:
  - jupyter=1.0.0
  - jupyterlab=2.1.1
  - pandas=1.0.3
  - numpy=1.18.1
  - pymc3=3.9.3
  - theano=1.0.4
  - scipy=1.2.1
  - seaborn=0.10.0
  - matplotlib=3.2.1
  - scikit-learn=0.22.2.post1
  - mkl-service=2.3.0
  - statsmodels=0.12.1
  - jupyter_contrib_nbextensions=0.5.1
  - xlrd=1.2.0
  - pytest=6.2.1
  - graphviz=2.42.3
  - python-graphviz=0.16


